project:
  type: website
  output-dir: docs

website:
  title: "Jia Wen Cheng"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: PROJECTS
      - hello.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



