project:
  type: website
  output-dir: docs

website:
  title: "Jia Wen Cheng"
  favicon: assets/logo1.png
  navbar:
    left:
      - href: index.qmd
        text: HOME
      - text: ABOUT ME
        menu:
          - href: resume.qmd
            text: CV
          - href: edu_intern.qmd
            text: Education & Internship
          - href: moreaboutme.qmd
            text: More About Me
      - href: skills.qmd
        text: SKILLS
      - href: projects/index.qmd
        text: PROJECTS
      - href: reflections.qmd
        text: REFLECTIONS
      - href: resources.qmd
        text: RESOURCES
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/jia-wen-cheng-2bba39265/
        target: _blank
      - icon: github
        href: https://github.com/jiawenc13
        target: _blank
      - icon: envelope
        href: mailto:jia.cheng5@mail.dcu.ie
      - icon: file-earmark-text
        href: assets/resume.pdf
        target: _blank

  page-footer:
    center: © Jia Wen Cheng 2025

format:
  html:
    theme:
      - Minty
      - styles.scss
      - brand
    mainfont: Montserrat
    
      

    css: styles.css
    toc: false

