project:
  type: website
  output-dir: docs

website:
  title: "Jia Wen Cheng"
  favicon: assets/logo1.png
  navbar:
    left:
      - href: index.qmd
        text: HOME
      - href: about.qmd
        text: ABOUT ME
      - href: projects.qmd
        text: PROJECTS
      - href: blogs.qmd
        text: BLOGS
      - href: resources.qmd
        text: RESOURCES
      - icon: github
        href: https://github.com/jiawenc13/jiawenc13.github.io
        target: _blank

      - hello.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



