project:
  type: website
  output-dir: docs

website:
  title: "Jia Wen Cheng"
  navbar:
    left:
      - href: index.qmd
        text: HOME
      - href: about.qmd
        text: ABOUT ME
      - href: projects.qmd
        text: PROJECTS
      - href: blogs.qmd
        text: BLOGS
      - href: media.qmd
        text: MEDIA
      - hello.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



