---
title: "Internship & Volunteer"
---
<div>
  <p>
As part of my course in Business Studies, I had the opportunity to go on INTRA, a year-long internship program that provided valuable hands-on experience in a professional environment. Throughout the placement, I have developed key professional skills from building a strong CV and tackling through interviews, to working effectively in a professional environment. 

My internship took place at Research Ireland, a funding organisation that supports researchers in the STEM fields in Ireland. I worked in the Programme Operations department, where I gained valuable, multifaceted experience across both administrative and logistical tasks. Throughout the internship, I had the opportunity to work with a range of tools, including Microsoft Excel, Word, Tableau and the company's grants and awards management system, which helped strengthen my technical and organizational skills in a professional setting. This role has allowed me to develop a well-rounded understanding of internal operations, while also strengthening my time management skills, stakeholder engagement, and ability to adapt to a dynamic work environment. I gained confidence in both collaborative teamwork and taking individual responsibility for tasks and projects.
  </p>
</div>

